import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

import '@stream-io/video-react-sdk/dist/css/styles.css'

import { Toaster } from "@/components/ui/sonner";
import { ConvexClientProvider } from "@/providers/convex-client-provider";
import { ModalProvider } from "@/providers/modal-provider";
import Loader  from '@/components/auth/loading'
import {StreamVideoProvider} from "@/providers/stream-client-provider";
import { Providers } from "@/providers/Providers";
import { SocketProvider } from "@/providers/socket-provider";
 
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WorkSpace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
        <Suspense fallback={<Loader />}>
          <ConvexClientProvider>
            <Providers>
              <SocketProvider>
              <Toaster />
              <ModalProvider />
              <StreamVideoProvider>
                <body className={inter.className}>
                  {children}
                </body>
              </StreamVideoProvider>
              </SocketProvider>
            </Providers>
          </ConvexClientProvider>
        </Suspense>
    </html>
  )
}
